### ISSUE TITLE
Add note in readme about v3

### ISSUE THREAD

**Issue by iansinnott** [carrot/roots-browserify#10]
Since roots-browserify only works with version 3 it would be helpful if there was a more prominent notice in this repository. I fumbled around with this extension and the latest NPM version for a while before noticing the v3 requirement since it looks like it only appears on the repo description. Just a thought.

But also if you guys will be releasing v3 on NPM soon then this will no longer be an issue.

**Comment by jenius** [comment]
Ah I'm sorry, good call. But yeah we are releasing v3 very soon so hopefully this will be resolved then!
