### ISSUE TITLE
after_hook seems to be called twice

### ISSUE THREAD

**Issue by samccone** [carrot/roots-browserify#18]
browserify is a costly operation, it seems like we are calling the after hook on file change twice.

any thoughts @jenius ?

**Comment by jenius** [comment]
I'm going to look into this today. Is there any more info you can drop for me here?

**Comment by jenius** [comment]
I am currently stripping watchify and implementing the cache the right way, through roots and its own watcher. While running tests I am unable to reproduce this issue, all hooks are running the right amount of times. Perhaps it was something to do with the double watcher, etc.

Going to close for now
