### ISSUE TITLE
Build with jQuery

### ISSUE THREAD

**Issue by lagden** [carrot/roots-browserify#20]
I try to use `roots-browserify` with `jQuery`, but doesn't work!!

**Comment by jenius** [comment]
Are you using a commonjs-compatible version of jquery?

**Comment by lagden** [comment]
I did exactly like that: https://github.com/iansinnott/roots-browserify-template

Well... The jQuery 2.1.4 has UMD declaration in the beginning!

I inserted some lines in the `package.json`, even so, it did not work!

```json
"browser": {
  "jquery": "./node_modules/jquery/dist/jquery.js"
}
```
Here is my simple test:
https://github.com/lagden/roots-test

Regards!

**Comment by jenius** [comment]
@lagden just pulled down your test repo and ran it on my machine. everything worked perfectly. What version of roots are you using?

**Comment by lagden** [comment]
@jenius I am using `roots@3.2.2`, `node@0.12.7` and `npm@2.13.4`

I did the test below:

Using the [ws](https://www.npmjs.com/package/local-web-server) as web-server.
**Works**
```
roots compile
ws -p 3132 -d public/
```

Using the `roots watch`.
**Fail**
```
roots watch -p 3132
```
---

Did you run using the `roots watch` and checked the console?

**Comment by jenius** [comment]
Downgrade to `roots@3.1.0` and try again. There's an issue with `3.2.x` right now thats causing some weird bugs.

**Comment by lagden** [comment]
`roots@3.1.0` Success!! :metal: 

Thanks for helping!
I will keep watching!
